module.exports = {
  ACTIONS: {
    RECOMMEND_UNIVERSITIES: "RECOMMEND_UNIVERSITIES",
    SHORTLIST_UNIVERSITY: "SHORTLIST_UNIVERSITY",
    LOCK_UNIVERSITY: "LOCK_UNIVERSITY",
    CREATE_TASK: "CREATE_TASK"
  }
};
