module.exports = {
  STAGES: {
    NOT_ONBOARDED: 0,
    PROFILE_READY: 1,
    DISCOVERING_UNIVERSITIES: 2,
    UNIVERSITY_LOCKED: 3,
    APPLICATION_PREP: 4
  },

  TASK_STATUS: {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED"
  }
};
